-- Run in Supabase SQL editor. Create one admin in Authentication > Users.
create extension if not exists "uuid-ossp";
create table if not exists site_settings (id uuid primary key default uuid_generate_v4(), key text unique not null, value jsonb not null default '{}'::jsonb, updated_at timestamptz default now());
create table if not exists skills (id uuid primary key default uuid_generate_v4(), name text not null, category text not null, proficiency int check(proficiency between 0 and 100), sort_order int default 0, created_at timestamptz default now());
create table if not exists projects (id uuid primary key default uuid_generate_v4(), slug text unique not null, title text not null, description text, category text, tools text[] default '{}', cover_url text, pdf_url text, featured boolean default false, sort_order int default 0, created_at timestamptz default now());
create table if not exists media (id uuid primary key default uuid_generate_v4(), project_id uuid references projects(id) on delete cascade, title text, url text not null, alt text, type text not null check(type in ('image','pdf')), category text, sort_order int default 0, created_at timestamptz default now());
create table if not exists certificates (id uuid primary key default uuid_generate_v4(), title text not null, organization text, issued_on date, description text, thumbnail_url text, pdf_url text, sort_order int default 0, created_at timestamptz default now());
create table if not exists messages (id uuid primary key default uuid_generate_v4(), name text not null, email text not null, subject text not null, message text not null, created_at timestamptz default now());
alter table site_settings enable row level security; alter table skills enable row level security; alter table projects enable row level security; alter table media enable row level security; alter table certificates enable row level security; alter table messages enable row level security;
create policy "public reads settings" on site_settings for select using (true); create policy "admin settings" on site_settings for all to authenticated using (true) with check (true);
create policy "public reads skills" on skills for select using (true); create policy "admin skills" on skills for all to authenticated using (true) with check (true);
create policy "public reads projects" on projects for select using (true); create policy "admin projects" on projects for all to authenticated using (true) with check (true);
create policy "public reads media" on media for select using (true); create policy "admin media" on media for all to authenticated using (true) with check (true);
create policy "public reads certificates" on certificates for select using (true); create policy "admin certificates" on certificates for all to authenticated using (true) with check (true);
create policy "admin reads messages" on messages for select to authenticated using (true);
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values ('portfolio','portfolio',true,10485760,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict do nothing;
create policy "public media access" on storage.objects for select using (bucket_id='portfolio'); create policy "admin upload media" on storage.objects for insert to authenticated with check (bucket_id='portfolio'); create policy "admin modify media" on storage.objects for update to authenticated using (bucket_id='portfolio'); create policy "admin delete media" on storage.objects for delete to authenticated using (bucket_id='portfolio');
