'use client';
import { ChangeEvent, useEffect, useState } from 'react';
import { createClient, isSupabaseConfigured } from '@/lib/supabase';
import { FileUp, LayoutDashboard, LogOut, Plus, Save, Trash2 } from 'lucide-react';
type Tab='Profile'|'Skills'|'Projects'|'Gallery'|'Certificates'|'CV'|'Contact'; type Row={id:string;name?:string;title?:string;category?:string;proficiency?:number;url?:string;cover_url?:string;[k:string]:unknown};
const tabs:Tab[]=['Profile','Skills','Projects','Gallery','Certificates','CV','Contact'];
const emptyProfile={name:'Ferdous Rahman Fakir',role:'Fashion Design Student',university:'Port City International University',program:'B.Sc. in Fashion Design & Technology (Honours)',year:'2nd Year',email:'',phone:'',location:'Chattogram, Bangladesh',hero:'Creating silhouettes, stories, and a more expressive future through fashion.'};
export default function Dashboard(){const [tab,setTab]=useState<Tab>('Profile'),[profile,setProfile]=useState(emptyProfile),[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const db=isSupabaseConfigured?createClient():null;
useEffect(()=>{load()},[tab]);async function load(){if(!db)return;setStatus('');if(tab==='Profile'||tab==='Contact'||tab==='CV'){const {data}=await db.from('site_settings').select('*');const d=Object.fromEntries((data||[]).map(x=>[x.key,x.value]));if(d.profile)setProfile(d.profile as typeof emptyProfile);if(tab==='CV'&&d.cv_url)setStatus(`Current CV: ${d.cv_url}`)}else {const table=tab==='Skills'?'skills':tab==='Projects'?'projects':tab==='Gallery'?'media':'certificates';let q=db.from(table).select('*').order('sort_order');if(tab==='Gallery')q=q.is('project_id',null);const {data,error}=await q;if(error)setStatus(error.message);setRows((data||[]) as Row[])}}
async function upsert(key:string,value:unknown){if(!db)return;setBusy(true);const {error}=await db.from('site_settings').upsert({key,value},{onConflict:'key'});setBusy(false);setStatus(error?error.message:'Saved. Refresh the public website to see the change.')}async function saveProfile(){await upsert('profile',profile)}
async function add(){if(!db)return;let table='',data:Record<string,unknown>={};if(tab==='Skills'){table='skills';data={name:'New Skill',category:'Fashion',proficiency:75,sort_order:rows.length}}if(tab==='Projects'){table='projects';const slug=`project-${Date.now()}`;data={slug,title:'New Project',description:'Describe this fashion project.',category:'Garments',tools:[],sort_order:rows.length}}if(tab==='Certificates'){table='certificates';data={title:'New Certificate',organization:'Organization',sort_order:rows.length}}if(!table)return;const {error}=await db.from(table).insert(data);setStatus(error?error.message:'Item created. Click its fields to edit.');load()}
async function saveRow(row:Row){if(!db)return;const table=tab==='Skills'?'skills':tab==='Projects'?'projects':tab==='Certificates'?'certificates':'media';const {id,...data}=row;const {error}=await db.from(table).update(data).eq('id',id);setStatus(error?error.message:'Saved.');}async function remove(id:string){if(!db||!confirm('Delete this item permanently?'))return;const table=tab==='Skills'?'skills':tab==='Projects'?'projects':tab==='Certificates'?'certificates':'media';const {error}=await db.from(table).delete().eq('id',id);setStatus(error?error.message:'Deleted.');load()}
async function upload(e:ChangeEvent<HTMLInputElement>,kind:'profile'|'gallery'|'cv'|'project'|'certificate'){const file=e.target.files?.[0];if(!file||!db)return;setBusy(true);const path=`${kind}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const {error}=await db.storage.from('portfolio').upload(path,file,{upsert:false});if(error){setStatus(error.message);setBusy(false);return}const {data:{publicUrl}}=db.storage.from('portfolio').getPublicUrl(path);if(kind==='profile'){const next={...profile,photo_url:publicUrl};setProfile(next);await upsert('profile',next)}else if(kind==='cv')await upsert('cv_url',publicUrl);else {const {error:insertError}=await db.from(kind==='gallery'?'media':'media').insert({title:file.name,url:publicUrl,type:file.type==='application/pdf'?'pdf':'image',category:kind==='gallery'?'Sketches':kind==='certificate'?'Certificate':'Project',sort_order:rows.length});setStatus(insertError?insertError.message:'File uploaded and added.')}setBusy(false);load()}
async function logout(){if(db)await db.auth.signOut();location.href='/admin/login'}
if(!isSupabaseConfigured)return <main className="grid min-h-screen place-items-center bg-[#0d0d0d] p-5 text-white"><div className="glass max-w-lg rounded-3xl p-8"><h1 className="font-display text-3xl">Connect Supabase first</h1><p className="mt-4 text-sm leading-6 text-zinc-400">Add your Project URL and anon key as Vercel environment variables, then redeploy. See the setup guide in README.</p></div></main>;
return <main className="min-h-screen bg-[#0d0d0d] text-white"><header className="flex h-16 items-center justify-between border-b border-white/10 px-5 sm:px-8"><a href="/" className="font-display font-bold">F<span className="text-red">.</span>F <span className="ml-2 text-xs font-normal text-zinc-500">ADMIN</span></a><button onClick={logout} className="flex items-center gap-2 text-xs text-zinc-400 hover:text-white"><LogOut size={15}/> Sign out</button></header><div className="flex"><aside className="hidden min-h-[calc(100vh-64px)] w-56 border-r border-white/10 p-4 md:block"><p className="eyebrow px-3 py-4">Content studio</p>{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`mb-1 flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm ${tab===t?'bg-red text-white':'text-zinc-400 hover:bg-white/5 hover:text-white'}`}><LayoutDashboard size={15}/>{t}</button>)}</aside><section className="w-full p-5 sm:p-9"><div className="mx-auto max-w-4xl"><p className="eyebrow">Manage content</p><h1 className="mt-2 font-display text-4xl font-bold">{tab}</h1><div className="mt-6 flex gap-2 overflow-x-auto md:hidden">{tabs.map(t=><button onClick={()=>setTab(t)} className={`whitespace-nowrap rounded-full px-3 py-2 text-xs ${tab===t?'bg-red':'bg-white/10'}`} key={t}>{t}</button>)}</div><div className="mt-8 rounded-2xl border border-white/10 bg-white/[.035] p-5 sm:p-7">{(tab==='Profile'||tab==='Contact')&&<ProfileForm profile={profile} setProfile={setProfile} contact={tab==='Contact'}/>} {tab==='CV'&&<Upload label="Upload replacement CV (PDF)" accept="application/pdf" onChange={e=>upload(e,'cv')}/>} {tab==='Gallery'&&<Upload label="Upload sketch, garment photo, mood board, technical sheet or PDF" onChange={e=>upload(e,'gallery')}/>} {tab==='Projects'&&<Upload label="Upload project image/PDF to gallery" onChange={e=>upload(e,'project')}/>} {tab==='Certificates'&&<Upload label="Upload certificate image/PDF" onChange={e=>upload(e,'certificate')}/>} {['Skills','Projects','Certificates','Gallery'].includes(tab)&&<><button onClick={add} className="btn btn-primary mt-5"><Plus size={14}/> Add {tab.slice(0,-1)}</button><div className="mt-5 space-y-3">{rows.map(r=><RowEditor key={r.id} row={r} tab={tab} onSave={saveRow} onDelete={remove}/>)}</div></>} {(tab==='Profile'||tab==='Contact')&&<><Upload label="Upload profile image" onChange={e=>upload(e,'profile')}/><button disabled={busy} onClick={saveProfile} className="btn btn-primary mt-6"><Save size={15}/> Save {tab}</button></>} {status&&<p className="mt-5 text-sm text-zinc-400">{status}</p>}</div></div></section></div></main>}
function ProfileForm({profile,setProfile,contact}:{profile:typeof emptyProfile;setProfile:(p:typeof emptyProfile)=>void;contact:boolean}){const fields=contact?['email','phone','location']:['name','role','university','program','year','hero'];return <div className="space-y-4">{fields.map(key=><label key={key} className="block text-sm capitalize text-zinc-300">{key.replace('_',' ')}<input value={profile[key as keyof typeof profile]} onChange={e=>setProfile({...profile,[key]:e.target.value})} className="mt-2 w-full rounded-xl border border-white/15 bg-black/25 p-3 text-sm text-white outline-none focus:border-red"/></label>)}</div>}
function Upload({label,accept='image/*,application/pdf',onChange}:{label:string;accept?:string;onChange:(e:ChangeEvent<HTMLInputElement>)=>void}){return <label className="mt-3 flex cursor-pointer items-center justify-between rounded-xl border border-dashed border-white/20 p-5 text-sm text-zinc-400 hover:border-red">{label}<FileUp size={19}/><input type="file" accept={accept} onChange={onChange} className="hidden"/></label>}
function RowEditor({row,tab,onSave,onDelete}:{row:Row;tab:Tab;onSave:(r:Row)=>void;onDelete:(id:string)=>void}){const [r,setR]=useState(row);useEffect(()=>setR(row),[row]);const field=tab==='Skills'?'name':'title';return <div className="flex flex-wrap items-center gap-2 rounded-xl border border-white/10 p-3"><input value={String(r[field]||'')} onChange={e=>setR({...r,[field]:e.target.value})} className="min-w-[170px] flex-1 rounded-lg bg-black/25 p-2 text-sm"/>{tab==='Skills'&&<><input value={String(r.category||'')} onChange={e=>setR({...r,category:e.target.value})} className="w-28 rounded-lg bg-black/25 p-2 text-sm"/><input type="number" value={Number(r.proficiency||0)} onChange={e=>setR({...r,proficiency:Number(e.target.value)})} className="w-20 rounded-lg bg-black/25 p-2 text-sm"/></>}<button onClick={()=>onSave(r)} className="rounded-lg bg-red px-3 py-2 text-xs">Save</button><button onClick={()=>onDelete(r.id)} aria-label="Delete" className="p-2 text-red"><Trash2 size={16}/></button></div>}
